### ISSUE TITLE
Transfer this repo to the WordPress organization?

### ISSUE THREAD

**Issue by ntwb** [WordPress/grunt-patch-wordpress#47]
We should transfer this repo to both the GitHub and npm orgs:

• GitHub organization: WordPress org https://github.com/WordPress 
• npm organization: https://www.npmjs.com/org/wordpress

Thoughts? Objections? cc @pento @aaronjorbin

**Comment by aaronjorbin** [comment]
@pento is going to be moving this to the github org

**Comment by aaronjorbin** [comment]
This has been transferred on Github. All core team members now have push access. 

As I'm not aware of anyway to transfer something on npm and have it properly redirect, I'm going to close this.  If there is any documentation on doing so in a way that won't break anything, please comment with it.
